### ISSUE TITLE
Compatibility?

### ISSUE THREAD

**Issue by Bear10** [davedevelopment/phpmig#105]
The readme suggests installing Pimple for a quick bootstrap however I think Pimple has been evolving and having more releases than that of phpmig.

As far as I've tested the compatibility for the bootstraped phpmig it only works with Pimple 1.1, is this correct? If so would be nice for either the documentation or the composer.json to have it.

**Comment by AntonLee** [comment]
What is exactly wrong, what you do and what error you get? I don't see Silex mentions in the readme.

**Comment by eman1986** [comment]
you won't as silex is a framework that uses pimple, phpmig should work on it as silex 1 did, but it also used an older version of pimple.

I get the error that it can find any migrations, I'm thinking that the version of pimple phpmig uses is not compatible with the newer version of pimple

**Comment by davedevelopment** [comment]
Closed by #110
