### ISSUE TITLE
Generate migration in local, apply them on a development server

### ISSUE THREAD

**Issue by phaberest** [davedevelopment/phpmig#107]
I'm trying to generate migration on my machine which is rsynced with a development server, but phpmig keeps yelling at me because it can't connect to mysql.

Is there a way to just create the migration files and *then* migrate them just like I'm used to with laravel?

**Comment by davedevelopment** [comment]
Maybe if you have an environment variable or something you could switch on?

``` php
// phpmig.php

if (getenv("IS_DEV")) {
    // use a dummy adapter so we don't need a db
    $container['phpmig.adapter'] = new Adapter\File\Flat(__DIR__ . DIRECTORY_SEPARATOR . 'migrations/.migrations.log');
} else {
    // normal adapter bootstrapping 
}

```

**Comment by phaberest** [comment]
Awesome, that did the trick.

Thank you Dave!
