### ISSUE TITLE
Problem with Eloquent 5.4

### ISSUE THREAD

**Issue by bigjoevtrj** [davedevelopment/phpmig#125]
Eloquent 5.4 has removed the method getFetchMode and it results in error:

[Symfony\Component\Debug\Exception\FatalThrowableError]                       
Call to undefined method Illuminate\Database\MySqlConnection::getFetchMode()

Just use PDO::FETCH_OBJ solve the problem, can you update the code?

**Comment by sim2github** [comment]
Problem is fixed in #122 but not released yet. You can use `"davedevelopment/phpmig": "dev-master"` or @davedevelopment please add tag `v1.3.1` - patched release.

**Comment by davedevelopment** [comment]
Done! https://github.com/davedevelopment/phpmig/releases/tag/v1.3.1
