### ISSUE TITLE
ability to access service locator?

### ISSUE THREAD

**Issue by Zxurian** [davedevelopment/phpmig#87]
I see that the readme uses Zend's autoloader. Is there any way to have access to the servicelocator from within the `up()` and `down()` methods?

**Comment by davedevelopment** [comment]
You can get access to anything you want really, the `ArrayAccess` return value of the `phpmig.php` bootstrap file is made available within the migrations.

``` php
// phpmig.php

$container = [];

// get service locator

$container['sl'] = $serviceLocator;

return $container;
```

``` php

// migration file

public function up()
{
    $this->get('sl')->foo();
}
```
