### ISSUE TITLE
Undocumented usage of `container.sets`

### ISSUE THREAD

**Issue by ddelnano** [davedevelopment/phpmig#90]
I have been very busy but am still working on the refactor PR but I just wanted to make sure I fully understood what this `set` parameter is for.  As far as I know, it seems to be undocumented.  I have seen it in multiple places but here is one just to illustrate what I am referring [to](https://github.com/davedevelopment/phpmig/blob/master/src/Phpmig/Console/Command/AbstractCommand.php#L141).  Is it just so you can have different sets of standalone migrations?

Just wanted to make sure I fully understood the intent so I can make sure to not break existing functionality.

**Comment by davedevelopment** [comment]
@ddelnano yes, see #54 for the PR with the contributors examples

**Comment by ddelnano** [comment]
Awesome sounds good!  Hopefully will have time this weekend to finish this PR up!
