### ISSUE TITLE
Same migrations on different databases

### ISSUE THREAD

**Issue by aik099** [davedevelopment/phpmig#95]
In a project of mine I'm planning to:

* store VCS revision info (commit_id, files changed, etc.) in an SQLite database
* there would be separate SQLite database per repository (easier, than having to add "repository_id" column to each table)
* have single set of migration scripts (via this library)

What I'm struggling at is how to make it all work considering, that:

* I don't know SQLite database location at the moment, when PHPMig library is initialized and therefore:
 * I can't use PHPMig CLI to create new migrations easily
 * I can't specify any DB in PHPMig config to create "migration" table in

Here is how I plan this to work: I call a method in my code like this `...->getDatabase('/path/to/db1.sqlite');` and will:
* if database is missing, then:
 * create an empty file
 * populate it with proper empty tables
 * return PDO class object
* if file is present, then:
 * open it
 * execute missing migrations (if any)
 * return PDO class object

**Comment by aik099** [comment]
Any suggestions?

**Comment by davedevelopment** [comment]
Heya, nothing off the top of my head, except for a wrapper script that writes the correct info out to a phpmig bootstrap file and then invokes phpmig with that file. 

This lib is currently heavily coupled to the bootstrap file, which makes this awkward, as mentioned in #75

**Comment by aik099** [comment]
What I turned up doing is:

* writing minimalistic solution that does exactly what's needed
* a `MigrationManager` class, that:
 * is initialized (constructor) with path to a folder containing migrations
 * has `createMigration` method that creates migration with a given name & type
 * has `run` method that accepts a context, which consists of database, container and whatever is needed
* separate runner classes for different migration types (e.g. `php` and `sql`)

Very simple stuff, but does what it's supposed to do.

You can see actual implementation at https://github.com/console-helpers/svn-buddy/tree/master/src/SVNBuddy/Database/Migration
